[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
dotenv = "0.15.0"

db_connector = { path = "../db_connector" }
serde = { version = "1.0.196", features = ["derive"] }
argon2 = "0.5.3"
diesel = "2.1.4"
uuid = { version = "1.7.0", features = ["v4"] }
anyhow = "1.0.79"
actix-web-validator = "5.0.1"
validator = { version = "0.16.1", features = ["derive"] }
chrono = "0.4.33"
actix-cors = "0.7.0"
jsonwebtoken = "9.2.0"
futures-util = "0.3.30"
lettre = { version = "0.11.4", features = ["native-tls"] }
derive_more = "0.99.17"
simplelog = "0.12.1"
base64 = "0.21.7"

[dev-dependencies]
rand = "0.8.5"
boringtun = "0.6.0"
rand_core = "0.6.4"

[profile.release]
opt-level = 3
lto = true
