[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
dotenv = "0.15.0"

db_connector = { path = "../db_connector" }
serde = { version = "1.0.196", features = ["derive"] }
argon2 = "0.5.3"
diesel = "2.1.4"
uuid = { version = "1.7.0", features = ["v4"] }
anyhow = "1.0.79"
actix-web-validator = "5.0.1"
validator = { version = "0.16.1", features = ["derive"] }
chrono = "0.4.33"
jsonwebtoken = "9.2.0"
