- name: Change production version
  hosts: staging
  tasks:
    - name: Update packages
      become: true
      ansible.builtin.apt:
        update_cache: yes
        upgrade: safe
        autoremove: true

    - name: Ensure needrestart is installed
      become: true
      ansible.builtin.apt:
        name: needrestart
        state: present
        update_cache: yes

    - name: Check if reboot is required
      shell:
        cmd: needrestart -b | awk '/NEEDRESTART-KEXP|NEEDRESTART-KCUR/ {print $2}'
      become: true
      register: reboot_required_file

    - name: Reboot if required
      reboot:
        msg: "Rebooting due to system updates"
        connect_timeout: 5
        reboot_timeout: 360
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      become: true
      when: reboot_required_file.stdout_lines[0] != reboot_required_file.stdout_lines[1]

    - name: Checkout remote access git
      ansible.builtin.git:
        repo: https://github.com/Tinkerforge/esp32-remote-access.git
        dest: /home/freddy/esp32-remote-access
        version: main
        update: yes
        clone: yes
      register: git_checkout

    - name: Verify checked out tag
      ansible.builtin.command: git describe --tags --exact-match
      args:
        chdir: /home/freddy/esp32-remote-access
      register: git_tag
      changed_when: false
      failed_when: git_tag.rc not in [0, 128]

    - name: checkout warp-charger git
      ansible.builtin.git:
        repo: https://github.com/Tinkerforge/warp-charger.git
        dest: /home/freddy/warp-charger
        version: master
        update: yes
        clone: yes

    - name: Stop Docker containers
      community.docker.docker_compose_v2:
        project_src: /home/freddy/esp32-remote-access/docker
        state: stopped

    - name: Pull and rerun docker images
      community.docker.docker_compose_v2:
        build: always
        pull: always
        project_src: /home/freddy/esp32-remote-access/docker

    - name: Show current tag
      ansible.builtin.debug:
        msg: "Checked out tag: {{ git_tag.stdout | default('none') }}"
